Add printer gadget and example
surban/usb-gadget pull request #13
Opened 2024-12-05 19:53 UTC by tuna-f1sh

Last one from me I think!

Gadget is fairly simple. Included example based on [prn_example](https://docs.kernel.org/6.12/usb/gadget_printer.html#example-code) in kernel docs. I put some const I used in the example that I think are useful in the lib too; ioctl ID bytes.

2024-12-05 23:48 UTC, surban requested changes
Minor changes.

2024-12-05 23:48 UTC, surban commented on examples/printer.rs
> +//! Creates and binds a printer gadget function, then reads data from the sysfs file created by the gadget to stdout. Will exit after printing a set number of pages.
```suggestion
//! Creates and binds a printer gadget function, then reads data from the device file created by the gadget to stdout. Will exit after printing a set number of pages.
```

2024-12-05 23:48 UTC, surban commented on examples/printer.rs
> +// Printer sysfs path - 0 assumes we are the only printer gadget!
```suggestion
// Printer device path - 0 assumes we are the only printer gadget!
```

2024-12-05 23:48 UTC, surban commented on examples/printer.rs
> +const SYSFS_PATH: &str = "/dev/g_printer0";
```suggestion
const DEV_PATH: &str = "/dev/g_printer0";
```

2024-12-05 23:48 UTC, surban commented on examples/printer.rs
> +    println!("Attempt open sysfs path: {}", SYSFS_PATH);
```suggestion
    println!("Attempt open device path: {}", DEV_PATH);
```

2024-12-05 23:48 UTC, surban commented on src/function/printer.rs
> +//! A sysfs file at /dev/g_printerN will be created for each instance of the function, where N instance number. See './examples/printer.rs' for an example.
```suggestion
//! A device file at /dev/g_printerN will be created for each instance of the function, where N instance number. See 'examples/printer.rs' for an example.
```

2024-12-05 23:48 UTC, surban commented on src/function/printer.rs
> +    /// Printer status flags https://www.usb.org/sites/default/files/usbprint11a021811.pdf
```suggestion
    /// [Printer status flags](https://www.usb.org/sites/default/files/usbprint11a021811.pdf)
```

2024-12-05 23:48 UTC, surban commented on src/function/printer.rs
> +
A `new` function could be useful, since I guess the `pnp_string` is optional.

2024-12-06 08:57 UTC, tuna-f1sh commented
Thanks. I've fed these changes back in.

2024-12-06 09:49 UTC, surban approved these changes

2024-12-06 09:50 UTC, surban commented
Thanks. 

Are there any gadgets left unimplemented? ;-)

2024-12-06 09:50 UTC, merged

2024-12-06 10:15 UTC, tuna-f1sh commented
Haha, I don't think so! Thanks for your help and support on these though. Learnt some things.